# Generated by Django 4.2.7 on 2023-12-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False, verbose_name='Is photo default')),
                ('image', models.ImageField(upload_to='avatars')),
            ],
            options={
                'verbose_name': "User's image",
                'verbose_name_plural': "Users' images",
            },
        ),
    ]
