# Generated by Django 4.2.7 on 2023-12-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('PE', 'Personal'), ('GR', 'Group'), ('CH', 'Channel'), ('BT', 'Bot')], default='PE', max_length=2),
        ),
    ]
