# Generated by Django 4.2.7 on 2023-12-17 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chat_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadRecept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Message read time')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='chat.message', verbose_name='Message')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message reader')),
            ],
            options={
                'verbose_name': 'Read receipt',
                'verbose_name_plural': 'Read receipts',
            },
        ),
    ]
