# Generated by Django 4.2.7 on 2023-12-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.image', verbose_name='User avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is user online'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_online_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last online datetime'),
        ),
    ]
